export const CREATE_MONDEL = "CREATE_MONDEL";
export const RETRIEVE_MONDELS = "RETRIEVE_MONDELS";
export const UPDATE_MONDEL = "UPDATE_MONDEL";
export const DELETE_MONDEL = "DELETE_MONDEL";
export const DELETE_ALL_MONDELS = "DELETE_ALL_MONDELS";